config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'statuses#new'
  resources :statuses
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
# frozen_string_literal: true

class Status < ApplicationRecord
  validates :date, presence: true
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :status
  validates :name, presence: true, length: { maximum: 100 }
  validates :pr, presence: true
  validates :hours, presence: true, numericality: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/statuses_controller.rb
# frozen_string_literal: true

class StatusesController < ApplicationController
  before_action :set_status, only: %i[show edit update destroy]

  def new
    @status = Status.new
    @tasks = @status.tasks.build
  end

  def index
    @statuses = Status.paginate(page: params[:page], per_page: 5)
  end

  def show
    @tasks = @status.tasks
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      StatusMailer.with(status: @status).new_status_email.deliver_later
      flash[:notice] = 'Status Created Successfully!'
      redirect_to @status
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @status.update(status_params)
      flash[:notice] = 'Status Updated Successfully'
      redirect_to @status
    else
      render 'edit'
    end
  end

  def destroy
    @status.destroy
    flash[:alert] = 'Status deleted successfully '
    redirect_to root_path
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:date, tasks_attributes: %i[id name pr hours _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/statuses_helper.rb
# frozen_string_literal: true

module StatusesHelper
end

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskSubmissionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <h3 class="alert-heading">Following errors prevented the <%= obj.class.name.downcase %> from being saved!</h3>
     <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/statuses/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @status %>
  <%= form_with(model: @status, local:true) do |f| %>
    <div class="input-group mt-5 mb-5">
      <div class="input-group-prepend">
        <%= f.label :date, class: "input-group-text shadow" %>
      </div>
      <%= f.date_field :date, class: "form-control shadow rounded" %>
    </div>
      
    <div>
      <div class="form-group">
        <%= f.fields_for :tasks do |task| %>
            <%= render "task_fields", :f => task %>      
        <% end %>  
      </div>
      <%= link_to_add_association f, :tasks do %>
        <button class="btn btn-success " >Add task</button>
      <% end %>
    </div> 
    <div class="d-flex justify-content-center mt-5">
      <%= f.submit "Send Status", class: "btn btn-lg btn-outline-secondary mr-5 mb-3" %>
      <button type="button" class="btn btn-secondary col-2 my-1 text-light " data-toggle="modal" data-target="#exampleModal">
        Preview Mail
      </button>
    </div>
  <% end %>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Training Status </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Hi Nishant sir, <br>
            <p class="ml-5">Please find the status for Today.</p>
            <p>
              <table class="table-success">
                <tr class="table-dark text-center">
                  <th>Tasks</th>
                  <th>PR Links</th>
                  <th>Hours</th>
                </tr>
                <% @status.tasks.each do |task| %>
                  <tr class="text-center">
                    <td><input type="text" class="form-control" id="text_name" disabled></td>
                    <td><input type="text" class="form-control" id="text_pr" disabled></td>
                    <td><input type="text" class="form-control" id="text_hours" disabled></td>
                <% end %>
              </table>
            </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-small" data-dismiss="modal">Alright!</button>
        </div>
      </div>
    </div>
  </div>    

<div class="d-flex justify-content-center mt-5">
  <h4 class>Click here to view status history</h4>
</div>
<div class="d-flex justify-content-center mt-1">  
  <%= link_to 'Status History', @status, class: "btn btn-small btn-info" %>
</div>

app/views/statuses/_task_fields.html.erb
<div class="container">
  <div class="nested-fields mb-5">
    <div class= "form-row">
      <div class="form-group col-md-4 mb-5">
        <%= f.label "Completed Tasks", class: "input-group" %>
        <%= f.text_field :name, class: "form-control shadow rounded", id: "task_name", placeholder: "Enter the task you did today" %>
      </div>
      <div class="form-group col-md-4 mb-5">
        <%= f.label "PR Link", class: "input-group" %>
        <%= f.url_field :pr, class: "form-control shadow rounded", id: "pr_link", placeholder: "Mention the Github PR" %>
      </div>
      <div class="form-group col-md-4 mb-5">
        <%= f.label "Hours Taken", class: "input-group" %>
        <%= f.number_field :hours, in:(0..24), step:"0.5", class: "form-control shadow rounded", id: "time", placeholder: "Enter the time taken" %>
      </div>
    </div>
    <div class="d-flex mb-3">  
      <%= link_to_remove_association "Delete task", f, class: "btn btn-danger" %>
    <div>  
  </div>
</div>

app/views/statuses/edit.html.erb
<div class="container-fluid">
    <h1 class = "text-center mt-5" >Status Update App</h1>
</div>
<div class="container-fluid">
    <h2 class = "text-center mt-5">Edit Status</h2>
</div>
<%= render 'form' %>

app/views/statuses/index.html.erb
<div class="container-fluid">
  <h1 class = "text-center mt-5" >Status Update App</h1>
</div>
<div class="container-fluid">
  <h1 class = "text-center mt-5 mb-5">Status History</h1>
</div>

<div class="container">
  <% @statuses.each do |status| %>
    <h3 class = "text-center" ><%= link_to status.date, status_path(status) %></h3>
    <div class = "table-responsive">
      <table class="table table-hover table-bordered ">
        <thead class="table table-dark text-center">
          <tr>
            <th>Tasks</th>
            <th>PR Link</th>
            <th>Time Taken</th>
          </tr>
       </thead> 
       <tbody class="table table-info text-center">
         <% status.tasks.each do |task| %>
           <tr>
             <td><%= task.name %></td>
             <td><%= link_to task.pr, task.pr, target: 'blank' %></td>
             <td><%= task.hours %></td>
           </tr>
         <% end %>
       </tbody>
      </table>
    </div>  
  <% end %>  
     
  <div class="apple_pagination mb-3 mt-3">
    <%= will_paginate @statuses, :container => false %>
  </div>
</div>

app/views/statuses/new.html.erb
<div class="container-fluid">
  <h1 class = "text-center mt-5" >Status Update App</h1>
</div>
<div class="container-fluid">
  <h2 class = "text-center mt-5">New Status Update</h2>
</div>
<%= render 'form' %>

app/views/statuses/show.html.erb
<div class="container-fluid">
  <h1 class = "text-center mt-5" >Status Update App</h1>
</div>
<div class="container-fluid">
  <h1 class = "text-center mt-5 mb-5">Displaying Status</h1>
</div>

  <h3 class = "text-center" > Date: <%= @status.date %></h3>
  
  <div class="container">
  <div class = "table-responsive">
    <table class="table table-hover table-bordered justify-content-center" >
      <thead class="table table-dark text-center">
        <tr>
          <th>Tasks</th>
          <th>PR Link</th>
          <th>Time Taken</th>
          <th>Actions</th>
        </tr>
      </thead>  
    
      <tbody class="table table-info text-center">
        <% @tasks.each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= link_to task.pr, task.pr, target: 'blank' %></td>
          <td><%= task.hours %></td>
          <td><%= link_to 'EDIT', edit_status_path(@status) %> / <%= link_to 'DELETE', status_path(@status), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
    
  <div class="d-flex justify-content-center mt-5">
    <h4 class>Click here to view status history</h4>
  </div>
  <div class="d-flex justify-content-center mt-1">  
    <%= link_to 'Status History', statuses_path, class: "btn btn-small btn-info" %>
  </div>
</div>   

app/views/tasks/index.html.erb
<div class="container-fluid">
    <h1 class = "text-center mt-5" >Status Update App</h1>
</div>
<div class="container-fluid">
    <h1 class = "text-center mt-5 mb-5">Displaying Status</h1>
</div>

<div class = "table-responsive">
  <table class="table table-hover table-bordered ">
    <thead class="table table-dark text-center">
      <tr>
        <th>Date</th>
        <th>Tasks</th>
        <th>PR Link</th>
        <th>Time Taken</th>
      </tr>
    </thead>  
  
    <tbody class="table table-info text-center">
      <% @tasks.each do |task| %>
      <tr>
        <td><%= task.date %></td>
        <td><%= task.title %></td>
        <td><%= task.pr %></td>
        <td><%= task.hours %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div> 